package router

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"
	"github.com/go-playground/validator/v10"
	"gorm.io/gorm"

	"github.com/tmsankram/gonotes/internal/auth"
	"github.com/tmsankram/gonotes/internal/config"
	"github.com/tmsankram/gonotes/internal/files"
	"github.com/tmsankram/gonotes/internal/middleware"
	"github.com/tmsankram/gonotes/internal/notes"
	"github.com/tmsankram/gonotes/internal/ui"
	"github.com/tmsankram/gonotes/internal/users"
	myval "github.com/tmsankram/gonotes/internal/validator"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "github.com/tmsankram/gonotes/docs" // IMPORTANT: docs generated by swag init
)

func New(db *gorm.DB) *gin.Engine {
	cfg := config.Load()
	app := newApplication(db, cfg)

	app.registerCustomValidators()
	app.registerGlobalMiddleware()
	app.router.Static("/static", "./ui/static")

	app.registerUtilityRoutes()
	app.registerAPIRoutes()
	app.registerUIRoutes()

	return app.router
}

type application struct {
	router   *gin.Engine
	cfg      *config.Config
	renderer *ui.Renderer
	services serviceContainer
}

type serviceContainer struct {
	notes *notes.Service
	users *users.Service
	files *files.Service
}

func newApplication(db *gorm.DB, cfg *config.Config) *application {
	renderer := ui.NewRenderer(ui.LoadTemplates())

	return &application{
		router:   gin.New(),
		cfg:      cfg,
		renderer: renderer,
		services: serviceContainer{
			notes: notes.NewService(db),
			users: users.NewService(db),
			files: files.NewService(),
		},
	}
}

func (a *application) registerCustomValidators() {
	if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
		_ = v.RegisterValidation("notest", myval.TitleNoTest)
	}
}

func (a *application) registerGlobalMiddleware() {
	a.router.Use(
		middleware.RequestID(),
		middleware.Logger(),
		middleware.Recovery(),
		ui.FlashMiddleware(),
		ui.SessionMiddleware(a.services.users),
	)
}

func (a *application) registerUtilityRoutes() {
	a.router.GET("/", func(c *gin.Context) {
		a.renderer.Page(c, "layout.html", gin.H{
			"Title": "Home",
		})
	})

	a.router.GET("/health", func(ctx *gin.Context) {
		ctx.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	a.router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}

func (a *application) registerAPIRoutes() {
	notes.NewHandler(a.services.notes).RegisterRoutes(a.router)
	files.NewHandler(a.services.files).RegisterRoutes(a.router)

	authHandler := auth.NewHandler(a.services.users)
	authHandler.RegisterPublicRoutes(a.router)
	authHandler.RegisterProtectedRoutes(a.router)

	auth.NewTOTPHandler(a.services.users).RegisterRoutes(a.router)

	oauthHandler := auth.NewOauthHandler(a.services.users, a.cfg)
	a.router.GET("/auth/google/login", oauthHandler.GoogleLogin)
	a.router.GET("/auth/google/callback", oauthHandler.GoogleCallback)
	a.router.GET("/auth/github/login", oauthHandler.GithubLogin)
	a.router.GET("/auth/github/callback", oauthHandler.GithubCallback)
}

func (a *application) registerUIRoutes() {
	authUI := ui.NewAuthUI(a.services.users, a.renderer)

	a.router.GET("/login", authUI.LoginPage)
	a.router.POST("/login", authUI.LoginPost)
	a.router.GET("/register", authUI.RegisterPage)
	a.router.POST("/register", authUI.RegisterPost)

	a.router.GET("/logout", a.logout)
	a.router.GET("/notes", a.notesPage)
}

func (a *application) logout(c *gin.Context) {
	c.SetCookie(ui.JWT_COOKIE, "", -1, "/", "", false, true)
	ui.Flash(c, "Logged out")
	c.Redirect(http.StatusFound, "/")
}

func (a *application) notesPage(c *gin.Context) {
	a.renderer.Page(c, "notes/list.html", gin.H{
		"Title": "Notes",
	})
}
